# Generated by Django 2.0 on 2020-02-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.IntegerField(help_text='Телефон'),
        ),
    ]
