# Generated by Django 2.0 on 2020-02-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20200225_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(help_text='Почта', max_length=254),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(help_text='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(help_text='Тема', max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_name',
            field=models.CharField(help_text='Ваше имя', max_length=30),
        ),
    ]
