# Generated by Django 2.0 on 2020-02-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20200225_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.CharField(help_text='Телефон', max_length=20),
        ),
    ]
