# Generated by Django 2.0 on 2020-02-25 18:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_is_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='products/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=smart_selects.db_fields.ChainedForeignKey(chained_model_field='Category', on_delete=django.db.models.deletion.CASCADE, show_all=True, to='product.SubCategory'),
        ),
    ]
