# Generated by Django 2.0 on 2020-02-27 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='url',
        ),
    ]
