# Generated by Django 2.0 on 2020-02-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_manufacturer_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='photo',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='image',
            field=models.ImageField(default=1, upload_to='manufacturer/'),
            preserve_default=False,
        ),
    ]
